# Análise Inicial do Dataset

## Objetivo

Este notebook tem como objetivo fazer a inspeção incial do conjunto de dados utlizado no projeto, indetificando sua estrutura, tabelas e relacionamentos.

Não serão realizadas limpezas e transformações nesta etapa. Foco em compreender os dados antes do desenvolvimento do processo ETL.

# Fonte dos dados

Dataset: Campeonato Brasileiro de Futebol (2003–2025)

Origem:
https://www.kaggle.com/datasets/adaoduque/campeonato-brasileiro-de-futebol

Repositório oficial:
https://github.com/adaoduque/Brasileirao_Dataset

In [3]:
import pandas as pd
from pathlib import Path

In [4]:
DATA_PATH = Path("../data/raw")

In [5]:
for arquivo in DATA_PATH.iterdir():
  print(arquivo.name)

campeonato-brasileiro-cartoes.csv
campeonato-brasileiro-estatisticas-full.csv
campeonato-brasileiro-full.csv
campeonato-brasileiro-gols.csv

# Carregamento dos dados

Nesta etapa são carregados os arquivos CSV do projeto para verificar sua estrutura inicial e confirmar que os dados estão acessíveis.

In [6]:
partidas = pd.read_csv(DATA_PATH / "campeonato-brasileiro-full.csv")
estatisticas = pd.read_csv(DATA_PATH / "campeonato-brasileiro-estatisticas-full.csv")
gols = pd.read_csv(DATA_PATH / "campeonato-brasileiro-gols.csv")
cartoes = pd.read_csv(DATA_PATH / "campeonato-brasileiro-cartoes.csv")

In [7]:
datasets = {
  "Partidas": partidas,
  "Estatísticas": estatisticas,
  "Gols": gols,
  "Cartões": cartoes,
}

for nome, df in datasets.items():
  print(f"{nome}: {df.shape[0]} linhas x {df.shape[1]} colunas")

Partidas: 9165 linhas x 17 colunas
Estatísticas: 18330 linhas x 13 colunas
Gols: 10820 linhas x 6 colunas
Cartões: 20953 linhas x 8 colunas

In [8]:
datasets["Partidas"].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9165 entries, 0 to 9164
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  9165 non-null   int64
 1   rodata              9165 non-null   int64
 2   data                9165 non-null   object
 3   hora                9165 non-null   object
 4   mandante            9165 non-null   object
 5   visitante           9165 non-null   object
 6   formacao_mandante   4190 non-null   object
 7   formacao_visitante  4190 non-null   object
 8   tecnico_mandante    4555 non-null   object
 9   tecnico_visitante   4555 non-null   object
 10  vencedor            9165 non-null   object
 11  arena               9165 non-null   object
 12  mandante_Placar     9165 non-null   int64
 13  visitante_Placar    9165 non-null   int64
 14  mandante_Estado     9165 non-null   object
 15  visitante_Estado    9165 non-null   object
 16  arrecadacao         380 non-null    float64
dtypes: float64(1), int64(4), object(12)
memory usage: 1.2+ MB

In [9]:
datasets["Estatísticas"].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18330 entries, 0 to 18329
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   partida_id       18330 non-null  int64
 1   rodata           18330 non-null  int64
 2   clube            18330 non-null  object
 3   chutes           18330 non-null  int64
 4   chutes_no_alvo   18330 non-null  int64
 5   posse_de_bola    7568 non-null   object
 6   passes           18330 non-null  int64
 7   precisao_passes  5264 non-null   object
 8   faltas           18330 non-null  int64
 9   cartao_amarelo   18330 non-null  int64
 10  cartao_vermelho  18330 non-null  int64
 11  impedimentos     18330 non-null  int64
 12  escanteios       18330 non-null  int64
dtypes: int64(10), object(3)
memory usage: 1.8+ MB

In [10]:
datasets["Gols"].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10820 entries, 0 to 10819
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   partida_id   10820 non-null  int64
 1   rodata       10820 non-null  int64
 2   clube        10820 non-null  object
 3   atleta       10820 non-null  object
 4   minuto       10820 non-null  object
 5   tipo_de_gol  1293 non-null   object
dtypes: int64(2), object(4)
memory usage: 507.3+ KB

In [11]:
datasets["Cartões"].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20953 entries, 0 to 20952
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   partida_id  20953 non-null  int64
 1   rodata      20953 non-null  int64
 2   clube       20953 non-null  object
 3   cartao      20953 non-null  object
 4   atleta      20947 non-null  object
 5   num_camisa  20567 non-null  float64
 6   posicao     19755 non-null  object
 7   minuto      20953 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.3+ MB

## Análise dos valores ausentes

O levantamento inicial identificou valores ausentes em diferentes atributos das tabelas. Nesta etapa, os valores serão apresentados de forma estruturada, permitindo comparar a quantidade e a proporção de dados ausentes em cada coluna.

A presença de valores ausentes não implica necessariamente em um problema de qualidade. Cada caso deverá ser analisado de acordo com o significado da variável e sua relevância para o projeto antes de definir qualquer estratégia de tratamento.

In [12]:
for nome, df in datasets.items():
    print(f"\n{nome.upper()}:")
    nulos = df.isnull().sum()
    print(nulos[nulos > 0] if nulos.any() else "Nenhum valor ausente.")

PARTIDAS:
formacao_mandante     4975
formacao_visitante    4975
tecnico_mandante      4610
tecnico_visitante     4610
arrecadacao           8785
dtype: int64

ESTATÍSTICAS:
posse_de_bola      10762
precisao_passes    13066
dtype: int64

GOLS:
tipo_de_gol    9527
dtype: int64

CARTÕES:
atleta           6
num_camisa     386
posicao       1198
dtype: int64

In [13]:
for nome, df in datasets.items():
    print(f"\n{nome.upper()}:")
    display(df.head(3))

PARTIDAS:

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,arrecadacao
0,1,1,29/03/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,Brinco de Ouro,4,2,SP,RJ,NaN
1,2,1,29/03/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,2,0,PR,RS,NaN
2,3,1,30/03/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,-,Maracanã,1,1,RJ,PR,NaN

ESTATÍSTICAS:

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,1,1,Vasco,0,0,NaN,0,NaN,0,0,0,0,0
1,1,1,Guarani,0,0,NaN,0,NaN,0,0,0,0,0
2,2,1,Athletico-PR,0,0,NaN,0,NaN,0,0,0,0,0

GOLS:

   partida_id  rodata       clube                   atleta minuto tipo_de_gol
0        4607       1  Fluminense             Rafael Sóbis     31         NaN
1        4607       1  Fluminense                     Fred     45     Penalty
2        4607       1  Fluminense  Nirley da Silva Fonseca     59  Gol Contra

CARTÕES:

,partida_id,rodata,clube,cartao,atleta,num_camisa,posicao,minuto
0,4607,1,Figueirense,Amarelo,Thiago Heleno,4.0,Zagueiro,44
1,4607,1,Figueirense,Amarelo,Paulo Roberto da Silva,28.0,NaN,66
2,4608,1,Internacional,Amarelo,Juan Silveira dos Santos,4.0,Zagueiro,20

In [14]:

for nome, df in datasets.items():
    print(f"{nome}: {df.columns.tolist()}\n")

Partidas: ['ID', 'rodata', 'data', 'hora', 'mandante', 'visitante', 'formacao_mandante', 'formacao_visitante', 'tecnico_mandante', 'tecnico_visitante', 'vencedor', 'arena', 'mandante_Placar', 'visitante_Placar', 'mandante_Estado', 'visitante_Estado', 'arrecadacao']

Estatísticas: ['partida_id', 'rodata', 'clube', 'chutes', 'chutes_no_alvo', 'posse_de_bola', 'passes', 'precisao_passes', 'faltas', 'cartao_amarelo', 'cartao_vermelho', 'impedimentos', 'escanteios']

Gols: ['partida_id', 'rodata', 'clube', 'atleta', 'minuto', 'tipo_de_gol']

Cartões: ['partida_id', 'rodata', 'clube', 'cartao', 'atleta', 'num_camisa', 'posicao', 'minuto']

### Observações: Como as tabelas se conectam

Olhando para as colunas retornadas pelo código, fica bem clara a arquitetura dos nossos dados e como vamos conseguir cruzar essas informações no futuro.

A tabela de **Partidas** funciona como o coração do projeto. Nela, cada jogo tem um identificador único, a coluna `ID`. Quando olhamos para as tabelas de detalhes (**Estatísticas**, **Gols** e **Cartões**), vemos que elas referenciam esse mesmo jogo através da coluna `partida_id`. É exatamente esse o elo que usaremos para fazer as junções (joins) durante a análise.

Um detalhe interessante: todas as tabelas vieram com a coluna de rodada escrita como `rodata` (com um pequeno erro de digitação da fonte original). Isso é algo que podemos padronizar na etapa de limpeza.

Além disso, as tabelas secundárias compartilham a coluna `clube`, o que vai ser excelente para quebrarmos as métricas e avaliarmos o desempenho de times específicos ao longo da temporada, vinculando os eventos (um gol, um cartão ou a posse de bola) aos times que estavam em campo. No geral, os dados estão bem estruturados para a modelagem.

## Inspeção das primeiras observações

As primeiras observações de cada tabela são apresentadas para verificar a estrutura dos registros e complementar a análise realizada com o `info()`.

In [15]:
for nome, df in datasets.items():
    print(f"\n{'=' * 50}")
    print(nome)
    print(f"{'=' * 50}")
    display(df.head())

==================================================
Partidas
==================================================

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,arrecadacao
0,1,1,29/03/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,Brinco de Ouro,4,2,SP,RJ,NaN
1,2,1,29/03/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,2,0,PR,RS,NaN
2,3,1,30/03/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,-,Maracanã,1,1,RJ,PR,NaN
3,4,1,30/03/2003,16:00,Goias,Paysandu,NaN,NaN,NaN,NaN,-,Serra Dourada,2,2,GO,PA,NaN
4,5,1,30/03/2003,16:00,Internacional,Ponte Preta,NaN,NaN,NaN,NaN,-,Beira Rio,1,1,RS,SP,NaN

==================================================
Estatísticas
==================================================

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,1,1,Vasco,0,0,NaN,0,NaN,0,0,0,0,0
1,1,1,Guarani,0,0,NaN,0,NaN,0,0,0,0,0
2,2,1,Athletico-PR,0,0,NaN,0,NaN,0,0,0,0,0
3,2,1,Gremio,0,0,NaN,0,NaN,0,0,0,0,0
4,3,1,Flamengo,0,0,NaN,0,NaN,0,0,0,0,0

==================================================
Gols
==================================================

,partida_id,rodata,clube,atleta,minuto,tipo_de_gol
0,4607,1,Fluminense,Rafael Sóbis,31,NaN
1,4607,1,Fluminense,Fred,45,Penalty
2,4607,1,Fluminense,Nirley da Silva Fonseca,59,Gol Contra
3,4608,1,Internacional,Charles Aránguiz,6,NaN
4,4612,1,Cruzeiro,Marcelo Moreno,90,NaN

==================================================
Cartões
==================================================

,partida_id,rodata,clube,cartao,atleta,num_camisa,posicao,minuto
0,4607,1,Figueirense,Amarelo,Thiago Heleno,4.0,Zagueiro,44
1,4607,1,Figueirense,Amarelo,Paulo Roberto da Silva,28.0,NaN,66
2,4608,1,Internacional,Amarelo,Juan Silveira dos Santos,4.0,Zagueiro,20
3,4608,1,Vitoria,Amarelo,Vinícius Santos Silva,NaN,NaN,82
4,4608,1,Internacional,Amarelo,Andrés D'Alessandro,10.0,Meio-campo,72

### Antes de fazermos qualquer limpeza, quero confirmar a integridade do relacionamento.

In [16]:
ids_partidas = set(partidas["ID"])

for nome, df in {
    "Estatísticas": estatisticas,
    "Gols": gols,
    "Cartões": cartoes
}.items():
    ids_relacionados = set(df["partida_id"])
    ids_sem_partida = ids_relacionados - ids_partidas

    print(f"{nome}: {len(ids_sem_partida)} partida(s) sem correspondência")

Estatísticas: 0 partida(s) sem correspondência
Gols: 0 partida(s) sem correspondência
Cartões: 0 partida(s) sem correspondência

### Resultado

Todas as tabelas relacionadas apresentaram correspondência com os identificadores existentes na tabela de partidas. Não foram encontrados registros em `estatisticas`, `gols` ou `cartoes` com `partida_id` sem correspondência em `partidas`.

Esse resultado indica que os identificadores utilizados nas tabelas possuem consistência básica para o relacionamento entre os dados.

## Verificação de registros duplicados

Nesta etapa será verificada a existência de registros duplicados nas tabelas, considerando a estrutura atual dos dados antes de qualquer transformação.

In [17]:
for nome, df in datasets.items():
    duplicados = df.duplicated().sum()
    print(f"{nome}: {duplicados} registro(s) duplicado(s)")

Partidas: 0 registro(s) duplicado(s)
Estatísticas: 0 registro(s) duplicado(s)
Gols: 0 registro(s) duplicado(s)
Cartões: 0 registro(s) duplicado(s)

### Resultado

Não foram identificados registros completamente duplicados em nenhuma das quatro tabelas analisadas.

A verificação foi realizada considerando todas as colunas de cada registro. Portanto, esta análise não identifica possíveis duplicidades parciais, que serão avaliadas posteriormente caso sejam relevantes para o processo de transformação dos dados.

## Análise dos valores ausentes

O levantamento inicial identificou valores ausentes em diferentes atributos das tabelas. Nesta etapa, os valores serão apresentados de forma estruturada, permitindo comparar a quantidade e a proporção de dados ausentes em cada coluna.

A presença de valores ausentes não implica necessariamente em um problema de qualidade. Cada caso deverá ser analisado de acordo com o significado da variável e sua relevância para o projeto antes de definir qualquer estratégia de tratamento.

In [18]:
for nome, df in datasets.items():
    nulos = df.isnull().sum()
    percentual = (nulos / len(df) * 100).round(2)

    resultado_nulos = pd.DataFrame({
        "Valores ausentes": nulos,
        "Percentual (%)": percentual
    })

    resultado_nulos = resultado_nulos[resultado_nulos["Valores ausentes"] > 0]

    print(f"\n{'=' * 50}")
    print(nome)
    print(f"{'=' * 50}")
    
    display(resultado_nulos)

==================================================
Partidas
==================================================

                    Valores ausentes  Percentual (%)
formacao_mandante               4975           54.28
formacao_visitante              4975           54.28
tecnico_mandante                4610           50.30
tecnico_visitante               4610           50.30
arrecadacao                     8785           95.85

==================================================
Estatísticas
==================================================

                 Valores ausentes  Percentual (%)
posse_de_bola               10762           58.71
precisao_passes             13066           71.28

==================================================
Gols
==================================================

             Valores ausentes  Percentual (%)
tipo_de_gol              9527           88.05

==================================================
Cartões
==================================================

            Valores ausentes  Percentual (%)
atleta                     6            0.03
num_camisa               386            1.84
posicao                 1198            5.72

## Distribuição dos valores ausentes ao longo do tempo

Como os dados abrangem diferentes períodos do Campeonato Brasileiro, será analisada a distribuição dos valores ausentes por temporada. O objetivo é verificar se a ausência de determinadas estatísticas está concentrada em períodos específicos.

In [19]:
partidas["ano"] = pd.to_datetime(
    partidas["data"],
    format="%d/%m/%Y"
).dt.year

partidas[["data", "ano"]].head()

         data   ano
0  29/03/2003  2003
1  29/03/2003  2003
2  30/03/2003  2003
3  30/03/2003  2003
4  30/03/2003  2003

In [20]:
estatisticas["ano"] = estatisticas["partida_id"].map(
    partidas.set_index("ID")["ano"]
)

estatisticas.groupby("ano")["posse_de_bola"].apply(
    lambda x: x.isnull().mean() * 100
).round(2)

ano
2003    100.00
2004    100.00
2005    100.00
2006    100.00
2007    100.00
2008    100.00
2009    100.00
2010    100.00
2011    100.00
2012    100.00
2013    100.00
2014     95.79
2015      0.00
2016      0.00
2017      0.26
2018      0.00
2019      6.05
2020      0.37
2021      0.00
2022      0.00
2023      0.00
2024    100.00
2025      1.58
Name: posse_de_bola, dtype: float64

In [21]:
estatisticas.groupby("ano")["precisao_passes"].apply(
    lambda x: x.isnull().mean() * 100
).round(2)

ano
2003    100.00
2004    100.00
2005    100.00
2006    100.00
2007    100.00
2008    100.00
2009    100.00
2010    100.00
2011    100.00
2012    100.00
2013    100.00
2014    100.00
2015    100.00
2016    100.00
2017    100.00
2018      0.00
2019      6.05
2020      0.37
2021      0.00
2022      0.00
2023      0.00
2024    100.00
2025      1.05
Name: precisao_passes, dtype: float64

### Observação sobre a disponibilidade das estatísticas

A análise temporal revelou que a disponibilidade das variáveis `posse_de_bola` e `precisao_passes` varia significativamente entre as temporadas.

Entre 2003 e 2013, ambas apresentam ausência total dos registros. A partir de 2018, passam a apresentar disponibilidade elevada, com algumas exceções em 2019, 2020, 2024 e 2025.

Esse comportamento indica que os valores ausentes estão relacionados à cobertura histórica da fonte de dados e não devem ser tratados automaticamente como zero ou substituídos sem considerar o contexto da variável.

Por esse motivo, a utilização dessas métricas no modelo preditivo deverá ser avaliada posteriormente, considerando sua disponibilidade e o impacto que o tratamento dos valores ausentes poderia causar na análise.

## Verificação da cardinalidade das tabelas

Nesta etapa será analisada a quantidade de registros associados a cada partida nas diferentes tabelas.

Espera-se que a tabela de partidas possua um único registro por partida e que a tabela de estatísticas possua dois registros por partida, correspondentes aos dois clubes envolvidos. As tabelas de gols e cartões possuem quantidade variável de registros por partida.

In [22]:
partidas["ID"].nunique(), len(partidas)

(9165, 9165)

In [23]:
estatisticas.groupby("partida_id").size().value_counts().sort_index()

2    9165
Name: count, dtype: int64

### Resultado

A tabela de estatísticas apresentou exatamente dois registros para cada uma das 9.165 partidas analisadas.

Esse resultado é consistente com a estrutura esperada dos dados, em que cada partida possui um registro de estatísticas para cada um dos dois clubes participantes.

In [24]:
partidas["ID"].nunique(), len(partidas)

(9165, 9165)

### Resultado

A tabela de partidas possui 9.165 registros e 9.165 identificadores únicos. Portanto, cada partida está representada uma única vez na tabela principal.

## Cardinalidade de gols e cartões

Nesta etapa será verificada a quantidade de registros de gols e cartões associados a cada partida.

Diferentemente da tabela de estatísticas, não existe uma quantidade fixa esperada de registros nessas tabelas, pois uma partida pode não possuir gols e pode apresentar diferentes quantidades de cartões.

In [25]:
gols_por_partida = gols.groupby("partida_id").size()

print(f"Partidas com pelo menos um gol registrado: {gols_por_partida.size}")
print(f"Maior quantidade de gols registrados em uma partida: {gols_por_partida.max()}")

Partidas com pelo menos um gol registrado: 4172
Maior quantidade de gols registrados em uma partida: 10

In [26]:
cartoes_por_partida = cartoes.groupby("partida_id").size()

print(f"Partidas com pelo menos um cartão registrado: {cartoes_por_partida.size}")
print(f"Maior quantidade de cartões registrados em uma partida: {cartoes_por_partida.max()}")

Partidas com pelo menos um cartão registrado: 4116
Maior quantidade de cartões registrados em uma partida: 16

### Resultado

A tabela de gols apresenta registros para 4.172 partidas, com no máximo 10 gols registrados em uma única partida.

A tabela de cartões apresenta registros para 4.116 partidas, com no máximo 16 cartões registrados em uma única partida.

Como gols e cartões são eventos que podem ocorrer em quantidades variáveis, a ausência de um `partida_id` nessas tabelas não será considerada, neste momento, um problema de integridade. Essa característica será considerada posteriormente durante a construção da base analítica.

## Análise da cobertura temporal de gols e cartões

A ausência de registros nas tabelas de gols e cartões não será inicialmente interpretada como ausência do evento. Como essas tabelas registram eventos ocorridos durante as partidas, uma quantidade elevada de partidas sem registros pode indicar tanto a ausência real do evento quanto uma limitação de cobertura da fonte.

Assim, será analisada a distribuição desses registros ao longo das temporadas para identificar possíveis períodos com cobertura incompleta.

In [27]:
gols["ano"] = gols["partida_id"].map(
    partidas.set_index("ID")["ano"]
)

cartoes["ano"] = cartoes["partida_id"].map(
    partidas.set_index("ID")["ano"]
)

In [28]:
gols_por_ano = gols.groupby("ano")["partida_id"].nunique()
cartoes_por_ano = cartoes.groupby("ano")["partida_id"].nunique()

total_partidas_por_ano = partidas.groupby("ano")["ID"].nunique()

cobertura = pd.DataFrame({
    "Partidas": total_partidas_por_ano,
    "Partidas com gols": gols_por_ano,
    "Partidas com cartões": cartoes_por_ano
}).fillna(0)

cobertura["% com gols"] = (
    cobertura["Partidas com gols"] / cobertura["Partidas"] * 100
).round(2)

cobertura["% com cartões"] = (
    cobertura["Partidas com cartões"] / cobertura["Partidas"] * 100
).round(2)

cobertura

,Partidas,Partidas com gols,Partidas com cartões,% com gols,% com cartões
ano,,,,,
2003,552,0.0,0.0,0.00,0.00
2004,552,0.0,0.0,0.00,0.00
2005,462,0.0,0.0,0.00,0.00
2006,380,0.0,0.0,0.00,0.00
2007,380,0.0,0.0,0.00,0.00
2008,380,0.0,0.0,0.00,0.00
2009,380,0.0,0.0,0.00,0.00
2010,380,0.0,0.0,0.00,0.00
2011,380,0.0,0.0,0.00,0.00
2012,380,0.0,0.0,0.00,0.00
2013,380,0.0,0.0,0.00,0.00
2014,380,348.0,371.0,91.58,97.63
2015,380,341.0,373.0,89.74,98.16
2016,379,352.0,372.0,92.88,98.15
2017,380,354.0,374.0,93.16,98.42
2018,380,337.0,377.0,88.68,99.21
2019,380,345.0,372.0,90.79,97.89
2020,268,246.0,266.0,91.79,99.25
2021,492,438.0,480.0,89.02,97.56
2022,380,354.0,373.0,93.16,98.16
2023,380,350.0,379.0,92.11,99.74
2024,380,354.0,379.0,93.16,99.74
2025,380,353.0,0.0,92.89,0.00

### Resultado

A análise temporal identificou uma limitação de cobertura nas tabelas de eventos.

Entre 2003 e 2013, não foram encontrados registros nas tabelas de gols e cartões. A partir de 2014, a tabela de gols passa a apresentar cobertura superior a 88% das partidas por temporada, enquanto a tabela de cartões apresenta cobertura superior a 97% até 2024.

Em 2025, a tabela de gols mantém cobertura de 92,89%, porém não foram encontrados registros na tabela de cartões.

Dessa forma, a ausência de registros nessas tabelas não será interpretada como ausência do evento. Os resultados indicam que a cobertura dos dados varia conforme o período, devendo essa limitação ser considerada na definição das variáveis e do recorte temporal da análise.

## Validação dos registros de gols por meio do placar

Para verificar se a ausência de registros na tabela de gols representa partidas sem gols ou uma possível falha de cobertura, será comparada a quantidade de partidas sem registros de gols com a quantidade de partidas cujo placar oficial foi 0 a 0.

Essa comparação será realizada apenas nas temporadas em que a tabela de gols apresenta registros.

In [29]:
partidas["sem_gols"] = (
    (partidas["mandante_Placar"] == 0) &
    (partidas["visitante_Placar"] == 0)
)

gols_por_partida = gols.groupby("partida_id").size()

partidas["tem_registro_gol"] = partidas["ID"].isin(gols_por_partida.index)

comparacao_gols = partidas.groupby("ano").agg(
    total_partidas=("ID", "count"),
    partidas_0x0=("sem_gols", "sum"),
    partidas_sem_registro_gol=("tem_registro_gol", lambda x: (~x).sum())
)

comparacao_gols

      total_partidas  partidas_0x0  partidas_sem_registro_gol
ano
2003             552            29                        552
2004             552            38                        552
2005             462            29                        462
2006             380            27                        380
2007             380            23                        380
2008             380            27                        380
2009             380            27                        380
2010             380            38                        380
2011             380            26                        380
2012             380            36                        380
2013             380            37                        380
2014             380            32                         32
2015             380            39                         39
2016             379            27                         27
2017             380            26                         26
2018             380            43                         43
2019             380            35                         35
2020             268            22                         22
2021             492            54                         54
2022             380            26                         26
2023             380            30                         30
2024             380            26                         26
2025             380            27                         27

### Resultado

A comparação entre os registros de gols e os placares das partidas apresentou correspondência exata entre 2014 e 2025. Em todas as temporadas desse período, a quantidade de partidas sem registro na tabela de gols foi igual à quantidade de partidas com placar de 0 a 0.

Esse resultado fornece evidência de consistência entre a tabela de gols e o placar oficial das partidas no período analisado.

Por outro lado, entre 2003 e 2013, todas as partidas não possuem registros na tabela de gols, embora existam partidas com diferentes resultados. Dessa forma, a tabela de gols não apresenta cobertura para esse período e não será utilizada para inferir eventos anteriores a 2014.

## Validação da cobertura de cartões

A tabela de cartões apresenta registros de eventos disciplinares associados às partidas. Para avaliar sua utilização na análise, será verificada sua cobertura por temporada e sua consistência com a estrutura das partidas.

A ausência de registros será tratada inicialmente como ausência de informação, e não como ausência de cartões, até que existam evidências que permitam essa interpretação.

In [30]:
cartoes.groupby("ano").size()

ano
2014    1774
2015    1993
2016    1827
2017    1888
2018    1954
2019    1765
2020    1299
2021    2268
2022    1971
2023    2118
2024    2096
dtype: int64

## Avaliação da utilização da tabela de cartões

A tabela de cartões apresenta registros entre 2014 e 2024, com quantidade variável de eventos por temporada. Entretanto, não foram encontrados registros para 2025.

Embora os cartões possam representar uma possível variável explicativa relacionada ao desempenho das equipes, essa informação não é essencial para responder ao problema de pesquisa definido. Além disso, a ausência de dados em 2025 introduziria uma limitação adicional para análises que utilizem a temporada mais recente.

Dessa forma, a tabela de cartões será mantida no conjunto de dados original e documentada durante a análise exploratória, mas não será priorizada na construção inicial da base analítica. Sua utilização poderá ser reconsiderada posteriormente caso apresente relevância para as hipóteses estabelecidas.

## Verificação da composição das temporadas

Antes da construção da base analítica, será verificada a quantidade de clubes participantes em cada temporada.

Essa etapa é necessária para identificar alterações no formato da competição e possíveis particularidades no número de partidas disputadas por temporada. Essas diferenças deverão ser consideradas na construção das métricas de desempenho e na definição da variável de rebaixamento.

In [31]:
clubes_por_ano = pd.concat([
    partidas[["ano", "mandante"]].rename(columns={"mandante": "clube"}),
    partidas[["ano", "visitante"]].rename(columns={"visitante": "clube"})
]).drop_duplicates()

clubes_por_ano.groupby("ano")["clube"].nunique()

ano
2003    24
2004    24
2005    22
2006    20
2007    20
2008    20
2009    20
2010    20
2011    20
2012    20
2013    20
2014    20
2015    20
2016    20
2017    20
2018    20
2019    20
2020    20
2021    24
2022    20
2023    20
2024    20
2025    20
Name: clube, dtype: int64

In [32]:
clubes_por_ano.groupby("ano")["clube"].nunique().value_counts().sort_index()

clube
20    19
22     1
24     3
Name: count, dtype: int64

## Construção da base de desempenho por clube e temporada

Após a validação inicial da estrutura das temporadas, inicia-se a transformação dos dados de partidas para uma unidade de análise composta por clube e temporada.

Essa transformação permitirá consolidar os resultados das partidas em métricas de desempenho de cada clube ao longo de uma temporada, que posteriormente poderão ser utilizadas na análise do risco de rebaixamento na temporada seguinte.

A primeira métrica calculada será o número de partidas disputadas por cada clube em cada temporada.

In [33]:
jogos_mandante = (
    partidas.groupby(["ano", "mandante"])
    .size()
    .reset_index(name="jogos")
    .rename(columns={"mandante": "clube"})
)

jogos_visitante = (
    partidas.groupby(["ano", "visitante"])
    .size()
    .reset_index(name="jogos")
    .rename(columns={"visitante": "clube"})
)

jogos_por_clube = pd.concat(
    [jogos_mandante, jogos_visitante]
)

jogos_por_clube = (
    jogos_por_clube
    .groupby(["ano", "clube"])["jogos"]
    .sum()
    .reset_index()
)

jogos_por_clube.head(10)

    ano         clube  jogos
0  2003  Athletico-PR     46
1  2003   Atletico-MG     46
2  2003         Bahia     46
3  2003   Corinthians     46
4  2003      Coritiba     46
5  2003      Criciuma     46
6  2003      Cruzeiro     46
7  2003   Figueirense     46
8  2003      Flamengo     46
9  2003    Fluminense     46

In [34]:
jogos_por_clube["jogos"].describe()

count    474.000000
mean      38.670886
std        4.732296
min       11.000000
25%       38.000000
50%       38.000000
75%       38.000000
max       50.000000
Name: jogos, dtype: float64

In [35]:
jogos_por_clube.groupby("ano")["jogos"].agg(["min", "max", "mean"])

      min  max  mean
ano
2003   46   46  46.0
2004   46   46  46.0
2005   42   42  42.0
2006   38   38  38.0
2007   38   38  38.0
2008   38   38  38.0
2009   38   38  38.0
2010   38   38  38.0
2011   38   38  38.0
2012   38   38  38.0
2013   38   38  38.0
2014   38   38  38.0
2015   38   38  38.0
2016   37   38  37.9
2017   38   38  38.0
2018   38   38  38.0
2019   38   38  38.0
2020   26   27  26.8
2021   11   50  41.0
2022   38   38  38.0
2023   38   38  38.0
2024   38   38  38.0
2025   38   38  38.0

In [36]:
jogos_por_clube[
    jogos_por_clube["ano"] == 2021
].sort_values("jogos")

      ano          clube  jogos
375  2021    Botafogo-RJ     11
380  2021       Coritiba     11
385  2021          Goias     11
393  2021          Vasco     12
378  2021    Chapecoense     38
381  2021         Cuiaba     38
388  2021      Juventude     38
370  2021     America-MG     38
377  2021          Ceara     49
376  2021     Bragantino     49
374  2021          Bahia     49
373  2021    Atletico-MG     49
379  2021    Corinthians     49
383  2021     Fluminense     49
372  2021    Atletico-GO     49
371  2021   Athletico-PR     49
391  2021      Sao Paulo     49
384  2021      Fortaleza     49
390  2021         Santos     49
387  2021  Internacional     49
392  2021          Sport     49
382  2021       Flamengo     50
389  2021      Palmeiras     50
386  2021         Gremio     50

## Considerações sobre a estrutura dos dados

A análise exploratória inicial permitiu identificar características importantes do conjunto de dados que deverão ser consideradas na construção da base analítica.

Foram identificadas diferenças na quantidade de clubes e partidas entre determinadas temporadas, além de períodos com diferentes níveis de cobertura das tabelas complementares de estatísticas, gols e cartões.

Essas diferenças não serão corrigidas diretamente nos dados brutos. A base original será preservada, e eventuais tratamentos necessários serão realizados posteriormente durante a etapa de preparação dos dados, de acordo com os requisitos da análise.

A partir desta etapa, a análise será direcionada à construção de uma base agregada por clube e temporada, unidade de análise adequada ao problema de pesquisa definido.

## Construção da Base Analítica (Issue #4)

A análise exploratória (Issue #2) identificou a estrutura, a integridade referencial e a
qualidade geral dos dados nas seções anteriores deste notebook, e está concluída.

A partir daqui, o notebook trata da construção da base analítica em nível clube-temporada,
necessária para a classificação e para a variável-alvo de rebaixamento.

O primeiro problema é de calendário: agrupar as partidas por ano civil (`data.dt.year`) não
corresponde às temporadas reais do campeonato. A Série A 2020, atrasada pela pandemia de
COVID-19, terminou em 25/02/2021, e a temporada 2021 começou em 29/05/2021, o que faz um
agrupamento por ano civil misturar as duas competições. A variável `temporada` corrige essa
distorção de calendário.

In [37]:
CUTOFF_TEMPORADA_2021 = pd.Timestamp("2021-05-29")

partidas["data_dt"] = pd.to_datetime(partidas["data"], format="%d/%m/%Y")
partidas["temporada"] = partidas["ano"].where(
    ~partidas["data_dt"].between("2021-01-01", CUTOFF_TEMPORADA_2021, inclusive="left"),
    2020
)

In [38]:
partidas_long = pd.concat([
    partidas[["temporada", "mandante"]].rename(columns={"mandante": "clube"}),
    partidas[["temporada", "visitante"]].rename(columns={"visitante": "clube"})
])

resumo_temporadas = (
    partidas_long
    .groupby(["temporada", "clube"])
    .size()
    .groupby("temporada")
    .agg(["min", "max", "count"])
)

resumo_temporadas.loc[[2020, 2021]]

           min  max  count
temporada
2020        38   38     20
2021        38   38     20

### Resultado

Após a correção, as 20 equipes apresentam exatamente 38 jogos nas temporadas 2020 e 2021
(mínimo e máximo iguais a 38 em ambas), confirmando que a variável `temporada` corrige
corretamente a distorção de calendário causada pela pandemia.

## Cobertura das Estatísticas Complementares

As colunas numéricas da tabela Estatísticas não possuem valores nulos, mas parte dos
registros está zerada por ausência de coleta, não por resultado real da partida. Esta
seção identifica, por ano, a proporção de registros totalmente zerados nas oito colunas
para definir a janela de dados confiável.

In [39]:
colunas_binarias = [
    "chutes", "chutes_no_alvo", "passes", "faltas",
    "cartao_amarelo", "cartao_vermelho", "impedimentos", "escanteios"
]

estatisticas["linha_totalmente_zerada"] = (estatisticas[colunas_binarias] == 0).all(axis=1)

cobertura_por_ano = (
    estatisticas
    .groupby("ano")["linha_totalmente_zerada"]
    .mean()
    .mul(100)
    .round(2)
)

cobertura_por_ano

ano
2003    100.00
2004    100.00
2005    100.00
2006    100.00
2007    100.00
2008    100.00
2009    100.00
2010    100.00
2011    100.00
2012    100.00
2013    100.00
2014     95.79
2015      0.00
2016      0.00
2017      0.26
2018      0.00
2019      6.05
2020      0.37
2021      0.00
2022      0.00
2023      0.00
2024    100.00
2025      0.00
Name: linha_totalmente_zerada, dtype: float64

### Resultado

As colunas de estatísticas complementares apresentam preenchimento zero (não real) em
2003–2013 (100%) e em 2024 (100%), com transição gradual em 2014 (95,79%). Entre 2015 e
2023, e também em 2025, o percentual de linhas totalmente zeradas é próximo de zero
(exceções pontuais: 2017 com 0,26%, 2019 com 6,05%, 2020 com 0,37%). A janela confiável
para uso de estatísticas complementares na base analítica é, portanto, 2015–2023 e 2025.